version: '3'
services:
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.92.0
    command: ["--set=service.telemetry.logs.level=debug"]
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
      - "18088:8088"
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
      - "18088:8088"
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=root
  drupal:
    #user: ubuntu
    build: &build-definition
      context: .
      dockerfile: ./Dockerfile
      args:
        - SPLUNK_ACCESS_TOKEN=$SPLUNK_ACCESS_TOKEN
        - SPLUNK_REALM=$SPLUNK_REALM
        - SERVICE_NAME=$SERVICE_NAME
    #image: drupal:latest
    depends_on:
      -  mysql
    ports:
      - 8080:80
    volumes:
      - ./web:/var/www/html
      - ./vendor:/opt/drupal/vendor
      - ./composer.json:/opt/drupal/composer.json
      - ./composer.lock:/opt/drupal/composer.lock
    links:
      - mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - SIGNALFX_TRACE_GLOBAL_TAGS="deployment.environment:$DEPLOYMENT_ENVIRONMENT

    